server.port=8301

spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:mariadb://localhost:3306/bizconnect
spring.datasource.username=lsh
spring.datasource.password=lsh
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.show-sql=true
logging.level.com.springboot.bizconnect=DEBUG

# JWT
jwt.secret=BizConnect-Secret-Key-For-JWT-Authentication-2024-Very-Long-Key-Here
jwt.access-token-expiration=1800000
jwt.refresh-token-expiration=604800000

# Redis
spring.data.redis.host=localhost
spring.data.redis.port=6379

# Cloudinary
cloudinary.cloud-name=dlccbzel2
cloudinary.api-key=463176193291357
cloudinary.api-secret=7oHAqOloiDK7k2cunO5VTXBHDgg
