spring.application.name=BizConnect

spring.datasource.url=jdbc:mariadb://localhost:3306/bizconnect
spring.datasource.username=lsh
spring.datasource.password=lsh
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver