spring.application.name=BizConnect
spring.profiles.active=${SPRING_PROFILE:dev}

server.port=${SERVER_PORT:8301}

spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:bizconnect}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:1234}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=alpha

spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect