spring.application.name=BizConnect

server.port=${SERVER_PORT:8301}

# Docker ?? ?? (???? ??)
spring.datasource.url=jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:bizconnect}
spring.datasource.username=${DB_USERNAME:lsh}
spring.datasource.password=${DB_PASSWORD:lsh}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# JPA ??
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect