server.port=8301

spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=jdbc:mariadb://localhost:3306/bizconnect
spring.datasource.username=lsh
spring.datasource.password=lsh
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.show-sql=true
logging.level.com.springboot.bizconnect=DEBUG