#spring.application.name=BizConnect
##spring.profiles.active=dev
#spring.profiles.active=prod
#springdoc.swagger-ui.path=/swagger-ui.html
#springdoc.swagger-ui.operations-sorter=alpha
#server.port=8301

spring.application.name=BizConnect
spring.profiles.active=${SPRING_PROFILE:dev}

springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=alpha
server.port=${SERVER_PORT:8301}